name: Readme Tree (Reusable on PR)

on:
  workflow_call:
    inputs:
      commit_message:
        type: string
        default: "chore: update README tree structure"
      exclude_pattern:
        type: string
        default: ".git|node_modules|.github"
      working_directory:
        type: string
        default: "."
permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme-on-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          fetch-depth: 0

      - name: Install tree
        run: sudo apt-get install -y tree

      # Parse repo/ref of THIS reusable workflow (e.g.
      # "Coalfire-CF/Actions/.github/workflows/org-tree-readme.yml@refs/heads/fix/org-tree-readme")
      - name: Derive actions repo/ref from workflow_ref
        id: derive
        run: |
          WF_REF="${{ github.workflow_ref }}"
          # extract part before "@"
          left="${WF_REF%@*}"
          # strip "/.github/workflows/..." -> owner/repo
          ACTIONS_REPO="${left%/.github/workflows/*}"
          # extract ref after "@"
          ACTIONS_REF="${WF_REF#*@}"
          echo "repo=$ACTIONS_REPO" >> $GITHUB_OUTPUT
          echo "ref=$ACTIONS_REF" >> $GITHUB_OUTPUT

      - name: Checkout Actions repo (to get script)
        uses: actions/checkout@v5
        with:
          repository: ${{ steps.derive.outputs.repo }}
          ref: ${{ steps.derive.outputs.ref }}
          path: _actions_repo
          fetch-depth: 1

      - name: Run updater
        id: run
        env:
          EXCLUDE_PATTERN: ${{ inputs.exclude_pattern }}
        run: |
          set +e
          bash "_actions_repo/scripts/update-readme-tree.sh"
          code=$?
          echo "exit_code=$code" >> $GITHUB_OUTPUT
          exit 0

      - name: Commit & push if changed
        if: ${{ steps.run.outputs.exit_code == '10' }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "${{ inputs.commit_message }}"
          git push origin HEAD
